base_url = "https://2kb.in"
title = "Sanoj Kumar C P"
theme = "hacker"
compile_sass = true
build_search_index = false

[markdown]
[markdown.highlighting]
theme = "github-dark"

[extra]
logo = ""
author = "Sanoj Kumar C P"
description = "Staff Software Engineer | Distributed Systems, EDA & Backend"
github = "twokaybee"
title_separator = "|"

menu = [
    { url = "/", name = "Home" }
]

social_links = [
    { name = "github", url = "https://github.com/twokaybee" },
    { name = "email", url = "mailto:sanoj2kb@gmail.com" }
]