name: Deploy Zola to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola
      - name: Build with Zola
        run: zola build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
